1. Read the dataset
2. Drop the columns which are unique for all users like IDs (2.5 points)
3. Distinguish the feature and target set (2.5 points)
4. Divide the data set into Train and test sets
5. Normalize the train and test data (2.5 points)
6. Initialize & build the model (10 points)
7. Optimize the model (5 points)
8. Predict the results using 0.5 as a threshold (5 points)
9. Print the Accuracy score and confusion matrix (2.5 points)

In [28]:
import keras

### Question
Read the dataset<br>
Drop the columns which are unique for all users like IDs (2.5 points)

In [29]:
import pandas as pd
import numpy as np

In [30]:
bank_df = pd.read_csv('bank.csv')

In [31]:
bank_df.head().T

                        0         1         2         3         4
RowNumber               1         2         3         4         5
CustomerId       15634602  15647311  15619304  15701354  15737888
Surname          Hargrave      Hill      Onio      Boni  Mitchell
CreditScore           619       608       502       699       850
Geography          France     Spain    France    France     Spain
Gender             Female    Female    Female    Female    Female
Age                    42        41        42        39        43
Tenure                  2         1         8         1         2
Balance                 0   83807.9    159661         0    125511
NumOfProducts           1         1         3         2         1
HasCrCard               1         0         1         0         1
IsActiveMember          1         1         0         0         1
EstimatedSalary    101349    112543    113932   93826.6   79084.1
Exited                  1         0         1         0         0

In [32]:
bank_df.shape

(10000, 14)

In [33]:
#Dropping Rownumber, CustomerID and Surname(This feature has no relevance to Predict Variable - Existed)
bank_df_new=bank_df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [34]:
bank_df_new.head().T

                      0        1       2        3        4
CreditScore         619      608     502      699      850
Geography        France    Spain  France   France    Spain
Gender           Female   Female  Female   Female   Female
Age                  42       41      42       39       43
Tenure                2        1       8        1        2
Balance               0  83807.9  159661        0   125511
NumOfProducts         1        1       3        2        1
HasCrCard             1        0       1        0        1
IsActiveMember        1        1       0        0        1
EstimatedSalary  101349   112543  113932  93826.6  79084.1
Exited                1        0       1        0        0

In [35]:
bank_df_new.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [36]:
bank_df_new.describe().T

,count,mean,std,min,25%,50%,75%,max
CreditScore,10000.0,650.528800,96.653299,350.00,584.00,652.000,718.0000,850.00
Age,10000.0,38.921800,10.487806,18.00,32.00,37.000,44.0000,92.00
Tenure,10000.0,5.012800,2.892174,0.00,3.00,5.000,7.0000,10.00
Balance,10000.0,76485.889288,62397.405202,0.00,0.00,97198.540,127644.2400,250898.09
NumOfProducts,10000.0,1.530200,0.581654,1.00,1.00,1.000,2.0000,4.00
HasCrCard,10000.0,0.705500,0.455840,0.00,0.00,1.000,1.0000,1.00
IsActiveMember,10000.0,0.515100,0.499797,0.00,0.00,1.000,1.0000,1.00
EstimatedSalary,10000.0,100090.239881,57510.492818,11.58,51002.11,100193.915,149388.2475,199992.48
Exited,10000.0,0.203700,0.402769,0.00,0.00,0.000,0.0000,1.00

### No Null Values. The df contains 10000 rows

### Question
Distinguish the feature and target set (2.5 points)

In [37]:
bank_df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [38]:
#Geography and gender are object variable and these need to be one hot encoded - Using get_dummies
bank_df_new = pd.get_dummies(bank_df_new, drop_first=True)

In [39]:
bank_df_new.head().T

                           0          1          2         3          4
CreditScore           619.00     608.00     502.00    699.00     850.00
Age                    42.00      41.00      42.00     39.00      43.00
Tenure                  2.00       1.00       8.00      1.00       2.00
Balance                 0.00   83807.86  159660.80      0.00  125510.82
NumOfProducts           1.00       1.00       3.00      2.00       1.00
HasCrCard               1.00       0.00       1.00      0.00       1.00
IsActiveMember          1.00       1.00       0.00      0.00       1.00
EstimatedSalary    101348.88  112542.58  113931.57  93826.63   79084.10
Exited                  1.00       0.00       1.00      0.00       0.00
Geography_Germany       0.00       0.00       0.00      0.00       0.00
Geography_Spain         0.00       1.00       0.00      0.00       1.00
Gender_Male             0.00       0.00       0.00      0.00       0.00

In [40]:
bank_df_new.shape

(10000, 12)

In [41]:
target = bank_df_new['Exited']
features = bank_df_new.drop('Exited',axis=1)

In [84]:
target.value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

### Question
Divide the data set into Train and test sets

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(features,target, test_size = 0.30, random_state = 7)

### Question
Normalize the train and test data (2.5 points)

In [44]:
from sklearn import preprocessing
normalized_features = preprocessing.normalize(features)
#Note it is better to normalize the full data and then use Train Test Split
#Re-applying Train test split on normalized features

In [45]:
X_train, X_test, y_train, y_test = train_test_split(normalized_features,target, test_size = 0.30, random_state = 7)

In [131]:
X_train

array([[[5.21547466e-03],
        [2.98027124e-04],
        [1.65570624e-05],
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[5.64961742e-03],
        [2.52571132e-04],
        [1.99398262e-05],
        ...,
        [6.64660873e-06],
        [0.00000000e+00],
        [6.64660873e-06]],

       [[4.91075252e-03],
        [3.87091775e-04],
        [7.59003480e-06],
        ...,
        [7.59003480e-06],
        [0.00000000e+00],
        [0.00000000e+00]],

       ...,

       [[4.23638988e-03],
        [2.16774336e-04],
        [3.71613148e-05],
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [6.19355246e-06]],

       [[5.37737031e-03],
        [2.66516896e-04],
        [7.05485901e-05],
        ...,
        [0.00000000e+00],
        [7.83873224e-06],
        [7.83873224e-06]],

       [[4.36238487e-03],
        [1.56444147e-04],
        [3.61024955e-05],
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [6.01708258e-06]]])

In [111]:
from keras.utils import np_utils

In [112]:
Y_train=np_utils.to_categorical(y_train)
Y_test=np_utils.to_categorical(y_test)

In [133]:
Y_train

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [110]:
X_train=np.expand_dims(X_train,axis=2)
X_test=np.expand_dims(X_test,axis=2)

In [116]:
from keras.models import Sequential
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import Flatten
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
from sklearn import metrics

### Question
Initialize & build the model (10 points)

In [47]:
from keras.models import Sequential
from keras.layers import Dense

In [117]:
# create model
model = Sequential()
model.add(Conv1D(filters=2,kernel_size=3,input_shape=(X_train.shape[1],X_train.shape[2]),padding='same',activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(12,activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(2, activation='sigmoid'))

W0728 13:12:32.382804 139698402219776 deprecation_wrapper.py:119] From /opt/conda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

In [119]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [134]:
# Fit the model
model.fit(X_train, Y_train, validation_data=(X_test,Y_test), epochs=10, batch_size=5)

Train on 7000 samples, validate on 3000 samples
Epoch 1/10
7000/7000 [==============================] - 2s 283us/step - loss: 0.5000 - acc: 0.7954 - val_loss: 0.4940 - val_acc: 0.7983
Epoch 2/10
7000/7000 [==============================] - 2s 281us/step - loss: 0.5000 - acc: 0.7954 - val_loss: 0.4947 - val_acc: 0.7983
Epoch 3/10
7000/7000 [==============================] - 2s 280us/step - loss: 0.4997 - acc: 0.7954 - val_loss: 0.4939 - val_acc: 0.7983
Epoch 4/10
7000/7000 [==============================] - 2s 293us/step - loss: 0.4999 - acc: 0.7954 - val_loss: 0.4946 - val_acc: 0.7983
Epoch 5/10
7000/7000 [==============================] - 2s 290us/step - loss: 0.5000 - acc: 0.7954 - val_loss: 0.4949 - val_acc: 0.7983
Epoch 6/10
7000/7000 [==============================] - 2s 279us/step - loss: 0.5000 - acc: 0.7954 - val_loss: 0.4942 - val_acc: 0.7983
Epoch 7/10
7000/7000 [==============================] - 2s 276us/step - loss: 0.4998 - acc: 0.7954 - val_loss: 0.4944 - val_acc: 0.7983
Epoch 8/10
7000/7000 [==============================] - 2s 263us/step - loss: 0.4996 - acc: 0.7954 - val_loss: 0.4942 - val_acc: 0.7983
Epoch 9/10
7000/7000 [==============================] - 2s 288us/step - loss: 0.5000 - acc: 0.7954 - val_loss: 0.4940 - val_acc: 0.7983
Epoch 10/10
7000/7000 [==============================] - 2s 285us/step - loss: 0.5001 - acc: 0.7954 - val_loss: 0.4943 - val_acc: 0.7983

### Question
Predict the results using 0.5 as a threshold (5 points) and Print the Accuracy score and confusion matrix (2.5 points)

In [135]:
model.predict(X_test)

array([[0.8502649 , 0.149604  ],
       [0.85026497, 0.14960396],
       [0.8502641 , 0.14960483],
       ...,
       [0.8524326 , 0.14765409],
       [0.85026526, 0.1496037 ],
       [0.85750043, 0.14308625]], dtype=float32)

In [136]:
y_predict=model.predict_classes(X_test)

In [137]:
type(y_predict)

numpy.ndarray

In [138]:
import numpy as np

In [139]:
unique, counts = np.unique(y_predict, return_counts=True)
dict(zip(unique, counts))

{0: 3000}

In [140]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [141]:
accuracy_score(y_test,y_predict)

0.7983333333333333

In [142]:
confusion_matrix(y_test,y_predict)

array([[2395,    0],
       [ 605,    0]])

In [143]:
cr=classification_report(y_test,y_predict)
print(cr)

              precision    recall  f1-score   support

           0       0.80      1.00      0.89      2395
           1       0.00      0.00      0.00       605

   micro avg       0.80      0.80      0.80      3000
   macro avg       0.40      0.50      0.44      3000
weighted avg       0.64      0.80      0.71      3000

/opt/conda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

### Question
Optimize the model (5 points)

In [ ]:
#Using K-Fold cross validation to optimize the model
from sklearn.model_selection import StratifiedKFold
import numpy
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
# split into input (X) and output (Y) variables
X = normalized_features
Y = target
# define 10-fold cross validation test harness
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
cvscores = []
for train, test in kfold.split(X, Y):
# create model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
model.fit(X[train], Y[train], epochs=150, batch_size=10, verbose=0)
# evaluate the model
scores = model.evaluate(X[test], Y[test], verbose=0)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
cvscores.append(scores[1] * 100)
print("%.2f%% (+/- %.2f%%)" % (numpy.mean(cvscores), numpy.std(cvscores)))