In [13]:
import pandas as pd
df1 = pd.read_csv('data.csv')
df1.head()

   SALESPERSON  Old Scheme (in thousands)  New Scheme (in thousands)
0            1                         57                         62
1            2                        103                        122
2            3                         59                         54
3            4                         75                         82
4            5                         84                         84

In [14]:
#Multiplying values by 1000 - Since data is in thousands
df1['Old Scheme (in thousands)'] = 1000*df1['Old Scheme (in thousands)']
df1['New Scheme (in thousands)'] = 1000*df1['New Scheme (in thousands)']
df1.head()

   SALESPERSON  Old Scheme (in thousands)  New Scheme (in thousands)
0            1                      57000                      62000
1            2                     103000                     122000
2            3                      59000                      54000
3            4                      75000                      82000
4            5                      84000                      84000

In [16]:
#Renaming columns since the values are multiplied by 1000
df1.rename(columns={"Old Scheme (in thousands)": "Old Scheme", "New Scheme (in thousands)": "New Scheme"}, inplace=True)
df1.head()

   SALESPERSON  Old Scheme  New Scheme
0            1       57000       62000
1            2      103000      122000
2            3       59000       54000
3            4       75000       82000
4            5       84000       84000

---------------------------------------------------------------------------------------------------------------------
<font size="5">Question 1:
Find the mean of old scheme and new scheme column. (5 points)</font>

In [18]:
print('The mean of the Old Scheme is',df1['Old Scheme'].mean())

The mean of the Old Scheme is 68033.33333333333

In [19]:
print('The mean of the New Scheme  is',df1['New Scheme'].mean())

The mean of the New Scheme  is 72033.33333333333

In [48]:
df1.head(20)

    SALESPERSON  Old Scheme  New Scheme
0             1       57000       62000
1             2      103000      122000
2             3       59000       54000
3             4       75000       82000
4             5       84000       84000
5             6       73000       86000
6             7       35000       32000
7             8      110000      104000
8             9       44000       38000
9            10       82000      107000
10           11       67000       84000
11           12       64000       85000
12           13       78000       99000
13           14       53000       39000
14           15       41000       34000
15           16       39000       58000
16           17       80000       73000
17           18       87000       53000
18           19       73000       66000
19           20       65000       78000

---------------------------------------------------------------------------------------------------------------------
<font size="5">Question 2: Use the five percent significance test over the data to determine the p value to check new scheme has significantly raised outputs? (10 points)</font>

In [62]:
#μ1 - Mean of Old Scheme sample
#μ2 - Mean of New Scheme sample
#Null Hypothesis - H0 => μ1 >= μ2 i.e μ2 - μ1 <= 0 i.e Mean Sum Assured in New Scheme is equal to Mean Sum Assured 
#in Old Scheme at the 0.05 level of significance
#Alternate Hypothesis - H1 =>  μ2 > μ1 i.e μ2 - μ1 > 0 i.e Mean Sum Assured in New Scheme is greater than Mean Sum Assured 
#in Old Scheme at the 0.05 level of significance
from scipy.stats import ttest_1samp, ttest_ind, mannwhitneyu, levene, shapiro, ttest_rel
t_statistic, p_value = ttest_rel(df1['New Scheme'],df1['Old Scheme'])
print(t_statistic, p_value)

1.5559143823544377 0.13057553961337662

In [37]:
one_tailed_p_value = p_value/2
print(one_tailed_p_value)

0.06528776980668831

---------------------------------------------------------------------------------------------------------------------
<font size="5">Question 3: What conclusion does the test (p-value) lead to? (2.5 points)</font>

---------------------------------------------------------------------------------------------------------------------
<font size="5">Answer: Note the test gave two tailed p-value. Our condition is one tailed (Only Greater than). One tailed p-value = p-value/2 = 0.0652. Since one tailed p-value > 0.05, do not reject Null Hypothesis. New Scheme DOES NOT have significantly raised outputs</font>

---------------------------------------------------------------------------------------------------------------------
<font size="5">Question 4: Suppose it has been calculated that in order for Titan to break even, the average output must increase by £5000 in the scheme compared to the old scheme. If this figure is alternative hypothesis, what is:
        a) The probability of a type 1 error? (2.5 points)

        b) What is the p- value of the hypothesis test if we test for a difference of $5000? (5 points)

        c) Power of the test (5 points)</font>

---------------------------------------------------------------------------------------------------------------------
<font size="5">Answer 4a) The Probability of type 1 error is α i.e. 5% </font>

---------------------------------------------------------------------------------------------------------------------
<font size="5">Question 4b) What is the p- value of the hypothesis test if we test for a difference of $5000? Note: For Titan to break evenit has been calculated that the average output must increase by £5000 (Atleast)</font>

In [45]:
#μ1 - Mean of Old Scheme sample
#μ2 - Mean of New Scheme sample
#μdiff - Mean of Difference of New Scheme sample and Old Scheme sample i.e. μdiff = μ2 - μ1
#Null Hyoothesis - μdiff <= 5000 i.e μdiff - 5000 <= 0
#Alternate Hypothesis - μdiff > 5000 i.e μdiff - 5000 > 0
#One tailed test (Right tailed)
t_statistic, p_value = ttest_1samp(df1['New Scheme'] - df1['Old Scheme'],5000)
print(t_statistic, p_value)

-0.3889785955886094 0.7001334912613286

In [47]:
#The p value above is two tailed p-value. One tailed p-value = p-value/2
oneTailedPValue = p_value /2
print('The p-value of the hypothesis test if we test for a difference of atleast $5000 to break even is',oneTailedPValue)

The p-value of the hypothesis test if we test for a difference of atleast $5000 to break even is 0.3500667456306643

In [50]:
#Since one tailed p-value is greater than 0.05, we DO NOT reject null hypothesis.
#Average output has not increased by $5000 to break even

---------------------------------------------------------------------------------------------------------------------
<font size="5">Question 4c) Power of the test (5 points)</font>

In [67]:
import numpy as np
# Calculating Power of Test
# Compute the difference in Means  and divide it by Standard Deviation - effect size
# Set the number of Observations - 30
# Set the alpha value and alternative values  'larger'
(np.mean(df1['New Scheme']) - np.mean(df1['Old Scheme']) - 5000) / np.sqrt(((30-1)*np.var(df1['New Scheme'])+(11-1)*np.var(df1['Old Scheme'])) / 30+30-2)
#(np.mean(df1['New Scheme'] - df1['Old Scheme']) - 5000) / np.std(df1['New Scheme'] - df1['Old Scheme'])

-0.03846508781993994

In [68]:
from statsmodels.stats.power import ttest_power
print('The power of the test is ', ttest_power(-0.0384, nobs=30, alpha=0.05, alternative='larger'))

The power of the test is  0.03213238669185958